name: Build and deploy Node.js app to Azure Web App - medscore-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm' # Add npm cache for faster builds

      - name: npm install, build, and test
        run: |
          npm ci # Use ci instead of install for cleaner, more reliable builds
          npm run build --if-present
          npm run test --if-present
        env:
          CI: true # Add CI environment variable

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        # Exclude node_modules and other unnecessary files
        run: |
          zip release.zip ./* -r \
          -x "node_modules/*" \
          -x ".git/*" \
          -x ".github/*" \
          -x "*.zip"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1 # Add retention period

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A8CAD92C12754EE687DE9C30565C4DD4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9AA5C785C9C84584937766A82760BDFC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_63E49092E3AB478CA79E87868E6EF165 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'medscore-api'
          slot-name: 'Production'
          package: .
